sudo: false

language: objective-c
os: osx
osx_image: xcode7.3

cache: false

addons:
  sauce_connect: true

before_install:
  - export PLUGIN_ROOT=$(pwd)
  - export LANG=en_US.UTF-8
  - brew update

install:
  - npm i -g ios-deploy --unsafe-perm=true
  - npm i -g cordova
  - npm i

before_script:
  - npm run lint

script:
  - wget http://dl.google.com/android/android-sdk_r24.4-macosx.zip
  - tar -xvf android-sdk_r24.4-macosx.zip

  - echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
  - echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter android-23
  - echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter extra-google-m2repository

  - export ANDROID_HOME=$PLUGIN_ROOT/android-sdk-macosx
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2

  - cd tests
  - cordova create hello com.example.hello HelloWorld
  - cd hello
  - cordova platform add android@5.2.2 --save
  - cordova platform add ios@4.2.1 --save
  - cordova requirements
  - cordova plugin add ../../ --variable ENABLE_CORDOVA_CALLBACK=true --save
  - cordova plugin list

  - cordova build android
  - npm run android-tamper
  - jarsigner -verbose -keystore $HOME/.android/debug.keystore -storepass android -keypass android $PLUGIN_ROOT/tests/android-tampered.apk androiddebugkey
  - export COMMIT_HASH=$(git rev-parse --short=16 HEAD)
  - curl -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY -X POST -H "Content-Type:application/octet-stream" https://saucelabs.com/rest/v1/storage/duddu/$COMMIT_HASH-android.apk?overwrite=true --data-binary @$PLUGIN_ROOT/tests/android-tampered.apk
  - npm run android-test

  - cordova build ios
  - npm run ios-tamper
  - cd platforms/ios/build/emulator
  - zip -r $PLUGIN_ROOT/tests/ios-tampered.zip HelloWorld.app
  - curl -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY -X POST -H "Content-Type:application/octet-stream" https://saucelabs.com/rest/v1/storage/duddu/$COMMIT_HASH-ios.zip?overwrite=true --data-binary @$PLUGIN_ROOT/tests/ios-tampered.zip
  - cd $PLUGIN_ROOT
  - npm run ios-test
