matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - tools
          - platform-tools
          - android-25
          - build-tools-25.0.2
      env: 
        - PLATFORM=android
        - PLATFORM_VERS=5.0
        - PACKAGE_EXT=apk
        - CACHE_NAME=android5
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env:
        - PLATFORM=ios
        - PLATFORM_VERS=9.3
        - PACKAGE_EXT=zip
        - CACHE_NAME=ios9
  exclude:
    - env: PLATFORM=none

env:
  matrix:
    - PLATFORM=none

branches:
  except:
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  sauce_connect: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -f $HOME/.gradle/caches/*/jarSnapshots/jarSnapshots.bin
  - rm -f $HOME/.gradle/caches/*/jarSnapshots/cache.properties*
  - rm -f $HOME/.gradle/caches/*/classAnalysis/classAnalysis.bin
  - rm -f $HOME/.gradle/caches/*/classAnalysis/cache.properties*
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - node_modules

before_install:
  - nvm install node

install:
  - npm install -g cordova
  - npm install

before_script:
  - npm run lint

script:
  - cordova create tests/hello com.example.hello HelloWorld
  - cd tests/hello
  - cordova platform add $PLATFORM --save
  - cordova plugin add ../../ --variable ENABLE_CORDOVA_CALLBACK=true --save
  - cordova plugin list
  - cordova prepare -verbose
  - cordova compile --debug $PLATFORM -verbose
  - npm run tamper-$PLATFORM
  - curl -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY -X POST -H "Content-Type:application/octet-stream" https://saucelabs.com/rest/v1/storage/duddu/$TRAVIS_JOB_ID-$PLATFORM.$PACKAGE_EXT?overwrite=true --data-binary @$TRAVIS_BUILD_DIR/tests/$PLATFORM-tampered.$PACKAGE_EXT
  - npm run appium-$PLATFORM
